export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_STAGE = 'SET_STAGE';
export const SET_STATE = 'SET_STATE';
export const SET_CORRECT_ANSWERS = 'STE_CORRECT_ANSWERS';
export const SET_CORRECT_WORD = 'SET_CORRECT_WORD';
export const UNDO_CORRECT_WORD = 'UNDO_CORRECT_WORD';
